### PR TITLE
Find quickest itinerary

### PR DESCRIPTION
**Pull request by tuukka**
This builds on top of #25 mainly as a different way to write `itineraryRows`: instead of assuming that the greedy algorithm works (which it does in the current Helsinki train network), compute all the possible itineraries using a cartesian product and pick the quickest one.

### CODE REVIEW

**Comment by tuukka** [comment]
Shall I rebase this to master?

**Comment by ohanhi** [comment]
@tuukka I think it'd really help me see what has changed in practice.

**Comment by tuukka** [comment]
Sure! Now it's a single commit on top of master.

**Comment by ohanhi** [comment]
Thanks, this is really nice! :+1:

**Comment by tuukka** [comment]
Thanks for merging and deploying!

**Pull request merged**
